export const orderTypes = {

    GET_PENDING_ORDERS_REQUEST: 'GET_PENDING_ORDERS_REQUEST',
    GET_PENDING_ORDERS_SUCCESS: 'GET_PENDING_ORDERS_SUCCESS',
    GET_PENDING_ORDERS_FAILURE: 'GET_PENDING_ORDERS_FAILURE',

    GET_PENDING_ORDER: 'GET_PENDING_ORDER',
    GET_COMPLETED_ORDER: 'GET_COMPLETED_ORDER',
    FILTER_PENDING_ORDER: 'FILTER_PENDING_ORDER',

    LOADING: "LOADING",
    
}